vscode:
  extensions:
    - streetsidesoftware.code-spell-checker
    - gruntfuggly.todo-tree
    - ikuyadeu.r
    - hbenl.vscode-test-explorer
    - streetsidesoftware.code-spell-checker-portuguese
    - streetsidesoftware.code-spell-checker-medical-terms
    - cschleiden.vscode-github-actions
    - editorconfig.editorconfig
    - donjayamanne.git-extension-pack
    - codezombiech.gitignore
    - james-yu.latex-workshop
    - richie5um2.vscode-sort-json
    - redhat.vscode-yaml
    - christian-kohler.path-intellisense
    - pkief.material-icon-theme
    - esbenp.prettier-vscode
    - foxundermoon.shell-format
    - alefragnani.bookmarks
    - ms-python.python
    - donjayamanne.githistory
    - eamodio.gitlens
    - ziyasal.vscode-open-in-github
    - https://marketplace.visualstudio.com/_apis/public/gallery/publishers/gabrielgrinberg/vsextensions/auto-run-command/1.6.0/vspackage
    - https://marketplace.visualstudio.com/_apis/public/gallery/publishers/spmeesseman/vsextensions/vscode-taskexplorer/2.5.1/vspackage
    - https://github.com/meakbiyik/vscode-r-test-adapter/releases/download/v0.4.1/vscode-r-test-adapter-0.4.1.vsix
    - github.vscode-pull-request-github
    - bierner.markdown-preview-github-styles

image: franzbischoff/false.alarm:latest

tasks:
  - name: Setup
    init: cp -R /home/docker/* /home/gitpod && chown -R gitpod:gitpod /home/gitpod
    before: /usr/lib/R/bin/Rscript -e renv::restore()
