vscode:
  extensions:
    - streetsidesoftware.code-spell-checker
    - gruntfuggly.todo-tree
    - hbenl.vscode-test-explorer
    - streetsidesoftware.code-spell-checker-portuguese
    - streetsidesoftware.code-spell-checker-medical-terms
    - cschleiden.vscode-github-actions
    - editorconfig.editorconfig
    - donjayamanne.git-extension-pack
    - codezombiech.gitignore
    - james-yu.latex-workshop
    - richie5um2.vscode-sort-json
    - redhat.vscode-yaml
    - christian-kohler.path-intellisense
    - pkief.material-icon-theme
    - esbenp.prettier-vscode
    - foxundermoon.shell-format
    # - alefragnani.bookmarks
    - richie5um2.vscode-sort-json
    - alefragnani.project-manager
    - ms-python.python
    - donjayamanne.githistory
    - eamodio.gitlens
    - ziyasal.vscode-open-in-github
    - github.vscode-pull-request-github
    - bierner.markdown-preview-github-styles
    - yzhang.markdown-all-in-one
    # r-test-adapter
    - https://public.am.files.1drv.com/y4m0E0Df_KJGcvscm4kDD-nm3XFuh8IPMY3i9CMg2Blmx-_KTAFMW_wSqPcbkoYqK3Tcmu-ZYkHhnAiQ89w2vnSH1x5Yuk2tbCu5eWV7tiP1iguUBJbK1lrRp_XX0imVX02twwOd7vp0DqJLPWeSR4mrLRQbE9owaubEsa_g6yWtX5ACvz8VuyOZjaJuDWL6lTdeBzZ7CwsBf_sCKotEf7X3HyuFIgmUvsLCFnOP5cDNpM
    # reload
    - https://public.am.files.1drv.com/y4mPqCbFjjCbDw0fWqpZ3rtFx6378Cvc8tfhOQ9AcLqsGn6M_isyCCR1Y2NnMRfUTXn2ZOH-AP3SOqILXz1gst3FDVIWNbOiPGLOjypsYV8PulsMUabmfJircP_cZJGmp1QYDJ2IYqrL1zD49wtODZ3Jqy4H6m9WDrpKe2g8q-4VpnQ_FnceVWvRNgspJ5bOP_rn_vUR2VtU9LFM4XO2rS9iO3c-hVmGuxFAdLvglJbGxQ
    # task explorer
    - https://public.am.files.1drv.com/y4m4l20O-R5He038ZN5FbaCB_2yw0N4eh4S50I71_I8oOANMWPqSYSdthrrxorRT9ofi1BNAJ2VmPqq2FUygFOCpG2Iz-tpb9FLl0k1me5tUqNE3TOtHOyDDGDL81bEnrpIpzN7O1C8UXLc4OHYim9iRJ6y9pZrDQ_kZrkYjj_QAbEOqKsQO71_RF5P-8s4fcX9xTi5x2tR7tzuIzKQRJS-OrJuRn--rv1NbnAZFWzAuSo
    # resource monitor
    - https://public.am.files.1drv.com/y4mj6G8A_g469xbFBaROtYEeJU3OO8boctnQBaPGBXWBrlMUonIbjHXrTI6bBOuA5BVtAKTgFqF_QFiGSTK9YFZrj9m-p3fwPmnBUcd1LqK2MvGf2sfeLajTAougRkjoV3xdQlf6adhyqACLCOP8UAvpzv2dUTOnXnRzcM1ku8f6lNJBBTTiHa0DVCjwTThsOIrqu8FoW5U4ox9BPNyKzn3hpLFYAX_WvMvS2KFpAxrccE
    # twilight theme
    - https://public.am.files.1drv.com/y4mUVtuvaRerchEF_vxe6EJWA_W0FoRAX9Vfqt-phbfVKbdGUdSjkX_EEUGr4p2nIDuiE0Bd5wQVnWRVXHcrWuqHKCjD3ljdxWxsUuPaMxsgcEByF52Ybr00e31qfYxQYR3CMWyddVPYRE4VJaKGCx54m8Z6uUUlJJv0tUwoKo_Qmhxr9DiBREfa7P_1v7Zi3JA0AvPXcd2Mmjz7wagAGNmtmynyzsWWoxT8wVQFbpHqkE

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
#     # enable for pull requests coming from this repo (defaults to true)
#     pullRequests: false
#     # enable for pull requests coming from forks (defaults to false)
#     pullRequestsFromForks: false
#     # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
#     addComment: false
#     # add a "Review in Gitpod" button to pull requests (defaults to false)
#     addBadge: false
#     # add a label once the prebuild is ready to pull requests (defaults to false)
#     addLabel: false

image:
  # franzbischoff/false.alarm-gitpod:stable
  file: .devcontainer/Dockerfile

tasks:
  - name: Setup
    init: |
      chmod 755 ./.devcontainer/configure_gitpod.sh
      ./.devcontainer/configure_gitpod.sh
  - name: tailscaled
    command: |
      if [ -n "${TAILSCALE_STATE_GITPOD_FALSEALARM}" ]; then
        # restore the tailscale state from gitpod user's env vars
        sudo mkdir -p /var/lib/tailscale
        echo "${TAILSCALE_STATE_GITPOD_FALSEALARM}" | sudo tee /var/lib/tailscale/tailscaled.state > /dev/null
      fi
      sudo tailscaled &
      exit
  - name: tailscale
    command: |
      if [ -n "${TAILSCALE_STATE_GITPOD_FALSEALARM}" ]; then
        sudo -E tailscale up
      else
        sudo -E tailscale up --hostname "gitpod-${GITPOD_GIT_USER_NAME// /-}-$(echo ${GITPOD_WORKSPACE_CONTEXT} | jq -r .repository.name)"
        # store the tailscale state into gitpod user
        gp env TAILSCALE_STATE_GITPOD_FALSEALARM="$(sudo cat /var/lib/tailscale/tailscaled.state)"
      fi
      exit
