#' Read the ECG file generated by WFDB2MAT.
#'
#' This function reads the tuple data.mat and data.hea that contains the signal and the header with information about
#' the signal.
#'

find_all_files <- function(path = getOption("target_ds_path", default = "inst/extdata/physionet"),
                           classes = c("all", "asystole", "bradycardia", "tachycardia", "fibv", "vtachy"),
                           limit_per_class = 1000,
                           long = FALSE) {
  "!DEBUG Starting process"

  checkmate::assert_directory_exists(path, access = "r")
  classes <- match.arg(classes, several.ok = TRUE)

  if (long) {
    files <- paste0(
      path, "/",
      list.files(here::here(path),
        pattern = "l\\.hea$"
      )
    )
  } else {
    files <- paste0(
      path, "/",
      list.files(here::here(path),
        pattern = "\\.hea$"
      )
    )
  }

  if (!("all" %in% classes)) {
    filtered <- NULL

    for (class in classes) {
      res <- switch(class,
        asystole = grep("a\\d*.\\.hea", files, value = TRUE),
        bradycardia = grep("b\\d*.\\.hea", files, value = TRUE),
        tachycardia = grep("t\\d*.\\.hea", files, value = TRUE),
        fibv = grep("f\\d*.\\.hea", files, value = TRUE),
        vtachy = grep("v\\d*.\\.hea", files, value = TRUE)
      )

      res <- head(res, limit_per_class)

      filtered <- c(filtered, res)
    }
    files <- filtered
  }



  return(files)
}
