---
editor_options:
  markdown:
    canonical: true
    mode: markdown
    wrap: 120
---

## Abstract {.unnumbered}

Currently, Point-of-Care (POC) ECG monitoring works either as plot devices or alarms for abnormal
cardiac rhythms using predefined normal trigger ranges and some rhythm analysis, which raises the
problem of false alarms. In comparison, complex 12-derivation ECG machines are not suitable to use
as simple monitors and are used with strict techniques for formal diagnostics. Thinking outside the
ICU setting, where high-end devices are available for patient monitoring, we aim to identify, on
streaming data, life-threatening hearth electric patterns using low CPU and memory, enabling ward
monitors, home devices and even wearable devices to be able to identify such events. The study
design is comparable to a diagnostic study, where high accuracy is essential. Physionet's 2015
challenge yielded very good algorithms for reducing false alarms. However, none of the authors
reported benchmarks, memory usage, robustness test, or context invariance that could assure its
implementation on small devices. We expect to identify the obstacles of detecting life-threatening
ECG changes within memory, space, and CPU constraints and using the proposed methods, assess the
feasibility of implementing the algorithm in the real world and other settings than ICU monitors.

