---
title: "Protocolo"
author: "Francisco Bischoff"
date: "6/5/2020"
output: pdf_document
---

# Identification of the project

# Title of the protocol (in Portuguese and English)

Anomaly detection (life-threathening patterns?) in Point-of-care ECG using efficient memory and processor power.

## Author(s)

Francisco Bischoff, Pedro Pereira Rodrigues

## Key-words

anomaly detection, ECG, fading factors, matrix profile, time series, point of care
(review with MESH terms)

## Project start date and duration

Authors (student and supervisors) must consider the dates defined in the scholar calendar, by FMUP

# Abstract or Summary (in Portuguese and English)

Currently Point of Care (POC) ECG monitoring works either as plotting devices and/or alarms for abnormal cardiac rhythms using predefined normal ranges. On the other hand, full 12-derivation ECG machines are complex to use as simple monitors and are used using strict techniques for formal diagnostics of hearth electric conduction pathologies, and the automatic diagnostics are derived from a full analysis of the 12 dimension data, after it is fully collected. Both systems doesn't handle disconnected leads and patient motions, being strictly necessary to have a good stable signal to allow diagnosis.

This research aims to identify on streaming data abnormal hearth electric patterns, specifically those who are life-threatening, being a reliable signal for Intensive Care Units to respond quickly to those situations.
This research also aims to accomplish this task using state of the art technology for time series analysis that allows minimum space and processor power to solve this problem.
In addition, we expect that fading factors can improve the state of the art technology.

<!-- Para background e probelms está ok. -->
<!-- Falta principalmente metodologia e resultados esperados -->
<!-- Matilde -->


# Rationale

<!-- The rationale allows the reader to establish the need for the study, meaning, an adequate explanation of the motivation of the present research / logical rational for the hypothesis raise is stated.   -->
<!-- For this, a summarized but adequate current state-of-art / knowledge is described where important facts are described, that should be supported by citations. Important figures and tables may be included as addenda. Most importantly, a clear and concise statement of the research idea or focus should be described (authors should also name what they are not addressing). -->
<!-- Students must include also some statement on the relevance of this thesis for his or her career and future work. -->
<!-- (Maximum of 500 Words) -->

Currently Point of Care (POC) ECG monitoring works either as plotting devices and/or alarms for abnormal cardiac rhythms using predefined normal ranges. On the other hand, full 12-derivation ECG machines are complex to use as simple monitors and are used using strict techniques for formal diagnostics of hearth electric conduction pathologies, and the automatic diagnostics are derived from a full analysis of the 12 dimension data, after it is fully collected. Both systems doesn't handle disconnected leads and patient motions, being strictly necessary to have a good stable signal to allow diagnosis.

# Research question and aims
<!-- The question should be adequately stated [identifying population, intervention, comparison (if applicable) and outcome(s)] (PICO). -->
<!-- The primary and secondary aims for each article that will be included in the Thesis must be stated. Up to 3 articles are recommended. Authors may consider limiting the number of specific aims (up to 3!) by each primary aim. -->
<!-- (Maximum of 200 words) -->

This research aims to identify on streaming data abnormal hearth electric patterns, specifically those who are life-threatening, being a reliable signal for Intensive Care Units to respond quickly to those situations.
This research also aims to accomplish this task using state of the art technology for time series analysis that allows minimum space and processor power to solve this problem.
In addition, we expect that fading factors can improve the state of the art technology.

# Background / Literature review

A literature review will be conducted to assess the state of the art for ECG automatic processing:

- The memory and space used to perform the main goal of the algorithm (sound an alarm for ex.)
- The algorithms used to identify ECG anomalies
- The algorithms used to identify specific diagnosis (like flutter, hyperkalemia, etc.)

A broad search will be conducted on Pubmed, Scopus, device manuals, etc.

Keywords: 
- ecg AND monitoring AND ICU
- ecg AND [time series]
- ecg AND automatic AND interpretation


<!-- The goal of this section is to include a critical literature review. Simply referring to previous work without commenting on the contribution that makes to your proposed project or without mentioning its limitations is neither significant nor useful.  -->
<!-- Students may consider a systematic approach but time frame for thesis presentation should be regarded carefully. If applicable, previous results of authors are viewed favourably. -->
<!-- (Maximum of 1000 words) -->


# Research plan and methods
<!-- This section should be clear and structured. Authors should present an overview of the methodologies to be adopted, which will be elaborated in detail for each task in the following subsection. -->
<!-- They may consider the structure presented below and argue if this chapter answers the questions posed by their hypothesis, if the design permits the achievement of project goals, and if the project output is generalizable or transferable. -->
<!-- (Maximum of 2000 words) -->

<!-- Importantly consider to repeat this section for each different study (I, II, … n)  according to the foreseen papers.  -->

## Type of study

<!-- Authors should clearly state the description and correct name for the study design. -->

## Selection of participants

<!-- Authors should name the target population and sampling methods.  Inclusion and exclusion criteria should be adequately described. -->

## Sample size

<!-- Authors should present an estimate of the sample size, indicating the references for data used in calculus. -->

## Data collection methods

<!-- A description of all procedures used for data collection should be made; authors should include references to unusual methods or instruments.  -->
<!-- Please note that if the protocol aim is a systematic review, methods used in searching, selecting, extracting and synthesizing data should be clearly stated. -->

## Variables

<!-- A clear definition of expected outcome, predictive/independent variables and other variables is expected. -->

## Statistical analysis

<!-- An appropriate statistical analysis, including descriptive and analytical methods, should be planned and described. -->

# Tasks, milestones and timeline
## Tasks

<!-- At this stage, authors should consider every task required to accomplish the implementation of protocol, measurements and thesis/manuscript writing. The sequence should be logical and the timeframe realistic. For each task authors should define (in no more than 400 words): -->
<!-- 1.Its denomination (task denomination should be self-explanatory); -->
<!-- 2.Duration (in months);  -->
<!-- 3.Aim and outputs for the task (and relation with the next task); -->
<!-- 4.Detailed description for procedures during the task; -->
<!-- 5.Dependence on other tasks; -->
<!-- 6.Human resources and level of autonomy of main author (the role each partner and institution will play in the task; -->
<!-- 7.Financial needs.  -->

<!-- Example of important tasks: -->
<!-- a.Proposal approval by a scientific committee of the Academic programme; -->
<!-- b.R&D and Ethical committees at Health institutions; -->
<!-- c.Financial support; -->
<!-- d.Patients enrolment; -->
<!-- e.Measurements; -->
<!-- f.Statistical analysis; -->
<!-- g.Manuscript and thesis writing -->

## Milestones

<!-- A milestone or marker is a date by which a certain objective should be achieved or a phase should be completed.  Enter a scheduled list of milestones that will allow to verify whether or not the project work is progressing towards the objective stated in the proposal. For each milestone, include a name (60 characters max.), a date and a description (300 characters max.) of what should be demonstrated or reported by that date.  -->

<!-- Examples of milestones:  -->
<!-- MilestoneDateNameDescription -->
<!-- M1Month 8Preparation of a test or questionnaireValidation of the measuring tool -->
<!-- M2Month 19Automatic counting systemA system that automatically counts the number of parts in the transporter and marks those that have manufacturing defects by analysing data from infrared sensors. -->

## Timeline
<!-- Authors should present a chart showing the schedule of tasks and milestone dates describing a timetable for the proposed research (attached timeline.xls). -->

# Budget

<!-- Authors should summarize in a Table the financial support needed to accomplish the project and present any current financial support. -->
<!-- BudgetJustificationFinancial support already obtained -->
<!-- Travel -->
<!-- Travel expenses, registration fees, daily allowances, and accommodation. -->
<!-- Consultants -->
<!-- Consulting expenses for project support. Foreign scientists residing outside Portugal may collaborate on the project and receive financial support for travel to Portugal and accommodation and may be paid for consulting work done on behalf of the project. -->
<!-- Goods and Services -->
<!-- Equipment -->

# Expected results and outcomes
## Expected results

<!-- Have you shown what the intended results will be, and their benefits and generalizability? Did you show you are aware of the limits to and value of the kinds of results you expect? What long-term intellectual and/or economic benefits can be derived from it?  -->

## Outcomes

<!-- This should be assumed by student and supervisor at first presentation. Two published manuscripts are mandatory, but three are recommended, as outcomes. -->

# References

<!-- References should adequately be structured according to Uniform Requirements (recommended style: APA). At least, rationale, background and methods should be adequately referenced. Authors should consider the use of a reference manager. -->
