#' Read the ECG file generated by WFDB2MAT.
#'
#' This function reads the tuple data.mat and data.hea that contains the signal and the header with information about
#' the signal.
#'
#' @export

make_idxs_split <- function(size, prop = 0.75) {
  sequence <- seq_len(size)

  training <- sort(sample(
    sequence,
    floor(size * prop)
  ))

  test <- sequence[!(sequence %in% training)]

  result <- list(training = training, test = test)

  return(result)
}
