#' Read the ECG file generated by WFDB2MAT.
#'
#' This function reads the tuple data.mat and data.hea that contains the signal and the header with information about
#' the signal.
#'
#' @export

compute_matrix_profile <- function(ecg_data, window_size = 200, n_workers = 4) {
  checkmate::qassert(ecg_data, "L")

  file <- names(ecg_data)
  names <- names(ecg_data[[file]])

  names <- setdiff(names, "time")

  for (n in names) {
    mp <- matrixprofiler::mpx(ecg_data[[file]][[n]], window_size = window_size, n_workers = n_workers, progress = FALSE)
    mp$w <- window_size
    attr(ecg_data[[file]][[n]], "mp") <- mp
  }

  return(ecg_data)
}
