#' Read the ECG file generated by WFDB2MAT.
#'
#' This function reads the tuple data.mat and data.hea that contains the signal and the header with information about
#' the signal.
#'
#' @export

find_all_files <- function(path = getOption("target_dataset_path", default = "inst/extdata/physionet/"), long = FALSE) {
  if (long) {
    files <- paste0(
      path,
      list.files(here::here(path),
        pattern = "l\\.hea$"
      )
    )
  } else {
    files <- paste0(
      path,
      list.files(here::here(path),
        pattern = "\\.hea$"
      )
    )
  }

  return(files)
}
