# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mass_weighted_rcpp <- function(data_fft, query_window, data_size, window_size, data_mean, data_sd, query_mean, query_sd, data_pre, weight, normalized) {
    .Call(`_false_alarm_mass_weighted_rcpp`, data_fft, query_window, data_size, window_size, data_mean, data_sd, query_mean, query_sd, data_pre, weight, normalized)
}

mass_absolute_rcpp <- function(data_fft, query_window, data_size, window_size, sumx2, sumy2) {
    .Call(`_false_alarm_mass_absolute_rcpp`, data_fft, query_window, data_size, window_size, sumx2, sumy2)
}

mass2_rcpp <- function(data_fft, query_window, data_size, window_size, data_mean, data_sd, query_mean, query_sd) {
    .Call(`_false_alarm_mass2_rcpp`, data_fft, query_window, data_size, window_size, data_mean, data_sd, query_mean, query_sd)
}

mass3_rcpp <- function(query_window, data_ref, data_size, window_size, data_mean, data_sd, query_mean, query_sd, k) {
    .Call(`_false_alarm_mass3_rcpp`, query_window, data_ref, data_size, window_size, data_mean, data_sd, query_mean, query_sd, k)
}

mass3_rcpp_parallel <- function(query_window, data_ref, data_size, window_size, data_mean, data_sd, query_mean, query_sd, k) {
    .Call(`_false_alarm_mass3_rcpp_parallel`, query_window, data_ref, data_size, window_size, data_mean, data_sd, query_mean, query_sd, k)
}

set_k_rcpp <- function(k, data_size, window_size) {
    .Call(`_false_alarm_set_k_rcpp`, k, data_size, window_size)
}

find_best_k_rcpp <- function(data_ref, query_ref, window_size) {
    .Call(`_false_alarm_find_best_k_rcpp`, data_ref, query_ref, window_size)
}

mass_pre_rcpp <- function(data_ref, query_ref, window_size) {
    .Call(`_false_alarm_mass_pre_rcpp`, data_ref, query_ref, window_size)
}

mass_pre_abs_rcpp <- function(data_ref, query_ref, window_size) {
    .Call(`_false_alarm_mass_pre_abs_rcpp`, data_ref, query_ref, window_size)
}

mass_pre_weighted_rcpp <- function(data_ref, query_ref, window_size, weight) {
    .Call(`_false_alarm_mass_pre_weighted_rcpp`, data_ref, query_ref, window_size, weight)
}

std_rcpp <- function(data, na_rm = FALSE) {
    .Call(`_false_alarm_std_rcpp`, data, na_rm)
}

list_to_matrix <- function(x) {
    .Call(`_false_alarm_list_to_matrix`, x)
}

mode_rcpp <- function(x) {
    .Call(`_false_alarm_mode_rcpp`, x)
}

znorm_rcpp <- function(data) {
    .Call(`_false_alarm_znorm_rcpp`, data)
}

normalize_rcpp <- function(data, min, max) {
    .Call(`_false_alarm_normalize_rcpp`, data, min, max)
}

binary_split_rcpp <- function(n) {
    .Call(`_false_alarm_binary_split_rcpp`, n)
}

ed_corr_rcpp <- function(data, window_size) {
    .Call(`_false_alarm_ed_corr_rcpp`, data, window_size)
}

corr_ed_rcpp <- function(data, window_size) {
    .Call(`_false_alarm_corr_ed_rcpp`, data, window_size)
}

inner_product <- function(a, b) {
    .Call(`_false_alarm_inner_product`, a, b)
}

sum_of_squares <- function(a) {
    .Call(`_false_alarm_sum_of_squares`, a)
}

fft_rcpp <- function(z, invert) {
    .Call(`_false_alarm_fft_rcpp`, z, invert)
}

mpx_rcpp <- function(data_ref, window_size, ez, s_size, idxs, euclidean, progress, constraint) {
    .Call(`_false_alarm_mpx_rcpp`, data_ref, window_size, ez, s_size, idxs, euclidean, progress, constraint)
}

mpxab_rcpp <- function(data_ref, query_ref, window_size, s_size, idxs, euclidean, progress) {
    .Call(`_false_alarm_mpxab_rcpp`, data_ref, query_ref, window_size, s_size, idxs, euclidean, progress)
}

mpx_rcpp_parallel <- function(data_ref, window_size, ez, s_size, idxs, euclidean, progress) {
    .Call(`_false_alarm_mpx_rcpp_parallel`, data_ref, window_size, ez, s_size, idxs, euclidean, progress)
}

mpxab_rcpp_parallel <- function(data_ref, query_ref, window_size, s_size, idxs, euclidean, progress) {
    .Call(`_false_alarm_mpxab_rcpp_parallel`, data_ref, query_ref, window_size, s_size, idxs, euclidean, progress)
}

scrimp_rcpp <- function(data_ref, query_ref, window_size, ez, s_size, pre_scrimp, progress) {
    .Call(`_false_alarm_scrimp_rcpp`, data_ref, query_ref, window_size, ez, s_size, pre_scrimp, progress)
}

scrimp_rcpp_parallel <- function(data_ref, query_ref, window_size, ez, s_size, progress) {
    .Call(`_false_alarm_scrimp_rcpp_parallel`, data_ref, query_ref, window_size, ez, s_size, progress)
}

scrimpab_rcpp <- function(data_ref, query_ref, window_size, s_size, progress) {
    .Call(`_false_alarm_scrimpab_rcpp`, data_ref, query_ref, window_size, s_size, progress)
}

stamp_rcpp <- function(data_ref, query_ref, window_size, ez, s_size, progress) {
    .Call(`_false_alarm_stamp_rcpp`, data_ref, query_ref, window_size, ez, s_size, progress)
}

stamp_rcpp_parallel <- function(data_ref, query_ref, window_size, ez, s_size, progress) {
    .Call(`_false_alarm_stamp_rcpp_parallel`, data_ref, query_ref, window_size, ez, s_size, progress)
}

stomp_rcpp <- function(data_ref, query_ref, window_size, ez, progress) {
    .Call(`_false_alarm_stomp_rcpp`, data_ref, query_ref, window_size, ez, progress)
}

stomp_rcpp_parallel <- function(data_ref, query_ref, window_size, ez, progress) {
    .Call(`_false_alarm_stomp_rcpp_parallel`, data_ref, query_ref, window_size, ez, progress)
}

movmean_rcpp <- function(data, window_size) {
    .Call(`_false_alarm_movmean_rcpp`, data, window_size)
}

movstd_rcpp <- function(data, window_size) {
    .Call(`_false_alarm_movstd_rcpp`, data, window_size)
}

movmean_std_rcpp <- function(data, window_size) {
    .Call(`_false_alarm_movmean_std_rcpp`, data, window_size)
}

movvar_rcpp <- function(data, window_size) {
    .Call(`_false_alarm_movvar_rcpp`, data, window_size)
}

movvar2_rcpp <- function(data, window_size) {
    .Call(`_false_alarm_movvar2_rcpp`, data, window_size)
}

movsum_rcpp <- function(data, window_size) {
    .Call(`_false_alarm_movsum_rcpp`, data, window_size)
}

movsum_ogita_rcpp <- function(data, window_size) {
    .Call(`_false_alarm_movsum_ogita_rcpp`, data, window_size)
}

precision_test_rcpp <- function(d) {
    .Call(`_false_alarm_precision_test_rcpp`, d)
}

movmin_rcpp <- function(data, window_size) {
    .Call(`_false_alarm_movmin_rcpp`, data, window_size)
}

movmax_rcpp <- function(data, window_size) {
    .Call(`_false_alarm_movmax_rcpp`, data, window_size)
}

movmean_weighted_rcpp <- function(data, window_size, eps) {
    .Call(`_false_alarm_movmean_weighted_rcpp`, data, window_size, eps)
}

movmean_fading_rcpp <- function(data, window_size, eps) {
    .Call(`_false_alarm_movmean_fading_rcpp`, data, window_size, eps)
}

movsum_weighted_rcpp <- function(data, window_size, eps) {
    .Call(`_false_alarm_movsum_weighted_rcpp`, data, window_size, eps)
}

movsum_fading_rcpp <- function(data, window_size, eps) {
    .Call(`_false_alarm_movsum_fading_rcpp`, data, window_size, eps)
}

movvar_weighted_rcpp <- function(data, window_size, eps) {
    .Call(`_false_alarm_movvar_weighted_rcpp`, data, window_size, eps)
}

movvar_fading_rcpp <- function(data, window_size, eps) {
    .Call(`_false_alarm_movvar_fading_rcpp`, data, window_size, eps)
}

muinvn_rcpp <- function(data, window_size) {
    .Call(`_false_alarm_muinvn_rcpp`, data, window_size)
}

muinvn_rcpp_parallel <- function(data, window_size) {
    .Call(`_false_alarm_muinvn_rcpp_parallel`, data, window_size)
}

zero_crossing_rcpp <- function(data, window_size) {
    .Call(`_false_alarm_zero_crossing_rcpp`, data, window_size)
}

