name: Binder
on:
  push:
    branches:
      - master
      - main

  workflow_dispatch:
  repository_dispatch:

concurrency:
  group: binder
  cancel-in-progress: true

jobs:
  Create-MyBinderOrg-Cache:
    runs-on: ubuntu-latest
    steps:
    - name: cache binder build on mybinder.org
      uses: jupyterhub/repo2docker-action@master
      with:
        NO_PUSH: true
        MYBINDERORG_TAG: ${{ github.event.ref }} # This builds the container on mybinder.org with the branch that was pushed on.
