name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - feature/classification
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "_*,.binder,.docker,.trunk,.vscode,renv,.github"
