name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - feature/classification
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          output_file: ".github/diagram.svg"
          excluded_globs: "**/*.{1,2,3,4,5,6,7,8,9};**/site_libs"
          excluded_paths: "_*,.binder,.docker,.trunk,.vscode,renv,.github"
