# This action will search for R code and apply the rules stored in the .lintr
# file using the `lintr` R package.

name: Lint

on:
  push:
    branches:
      - main
      - master
      - develop

  workflow_dispatch:
  repository_dispatch:

jobs:
  lint:
    runs-on: self-hosted
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - name: Checking out shallow repository
        uses: actions/checkout@v2

      - run: git branch

      - name: Install System dependencies
        run: |
          sudo apt-fast update
          sudo apt-fast install -y libgit2-dev libharfbuzz-dev libcurl4-openssl-dev \
          libfribidi-dev libzmq3-dev

      - name: Setting up R installation
        uses: r-lib/actions/setup-r@v1

      - name: Cache R packages
        uses: actions/cache@v2.1.4
        id: cache-packages
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}-targets-v2
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install dependencies
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          Sys.unsetenv("GITHUB_PAT")
          renv::restore()
        shell: Rscript {0}

      - name: Lint
        run: |
          for(i in c("analysis", "R", "review", "thesis", "output")) {
            lintr::lint_dir(i)
          }
        shell: Rscript {0}
