name: Workflowr

on:
  workflow_run:
    workflows:
      - Targets
    branches:
      - develop
    types:
      - completed

  workflow_dispatch:
  repository_dispatch:

jobs:
  workflowr:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && contains(github.event.head_commit.message, 'workflowr') }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - name: Checking out deep repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 ## all history
          ref: ${{ github.event.workflow_run.head_branch }}

      - run: git branch

      - name: Install System dependencies
        run: |
          sudo apt-fast update
          sudo apt-fast install -y libgit2-dev libharfbuzz-dev libcurl4-openssl-dev \
          libfribidi-dev libzmq3-dev

      - name: Setting up R installation
        uses: r-lib/actions/setup-r@v1

      - name: Setting up pandoc and pandoc-citeproc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Cache R packages
        uses: actions/cache@v2.1.4
        id: cache-packages
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}-targets-v2
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install dependencies
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          Sys.unsetenv("GITHUB_PAT")
          renv::restore()
        shell: Rscript {0}

      - name: Configure git
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"

      - name: Knit thesisdown
        run: |
          bookdown::render_book("index")
        shell: Rscript {0}

      - name: Stage thesisdown changes
        run: |
          git add --all -- ':!renv'

      - name: Build workflowr that creates the commit
        run: workflowr::wflow_publish(all = TRUE, update = TRUE, verbose = TRUE)
        shell: Rscript {0}

      - name: Push changes
        run: |
          git push
